### ISSUE TITLE
underscore vs point as separator in variable names

### ISSUE THREAD

**Issue by einarhjorleifsson** [fishvice/mar#12]
would be nice if user had the choice in tbl_mar to get the variable names as returned by e.g. fjolst::lesa.stovar. e.g. synis.id instead of synis_id.
reason being - the latter breaks older code routine
e

**Comment by bthe** [comment]
This is simply solved using the following command

```
tbl_mar(mar,'some_table_in_the_database') %>%
    select_all(function(x) gsub('_','.',x))
```
we could wrap this in a special function? Something like:

```
to_fjolst <- function(x){
    x %>% select_all(function(x) gsub('_','.',x))
}
```

**Comment by einarhjorleifsson** [comment]
this simple - nice.

may be call the wrapper cn_fjolst (cn standing for column names). thinking about another wrapper function(s) cn_iso and/or cn_english. the former is linked to my thinking of standardizing variable "keys", like veidarf/veidarfaeri becomes gid (gear id), teg/tegund/fteg becomes sid (species id), skipnr/skip_nr becomes vid (vessel id), etc.

e

**Comment by einarhjorleifsson** [comment]
added cn_fjolst, cn_mar
e
