### ISSUE TITLE
defunct select_ og mutate_

### ISSUE THREAD

**Issue by einarhjorleifsson** [fishvice/mar#14]
nú er 'dply' kominn í 0.7.0, og ég fæ þetta í einhverri gagnasókn:
```
> con <- connect_mar()
> afli_afli(con) %>%
+   filter(tegund == 130) %>%
+   left_join(afli_stofn(con)) %>%
+   left_join(afli_toga(con)) %>%
+   filter(ar %in% 2009:2011,
+     veidarf == 7,
+     !is.na(breidd),
+     !is.na(lengd),
+     afli > 0) %>%
+   select(-c(sokntegund,tegund,afli,medalthyngd_gr,astand,magn)) %>%
+   left_join(afli_afli(con)) %>%
+   mutate(lat = breidd, lon = lengd, yyyy = ar,
+     mm = man, date = vedags, ldate = ldags) %>%
+   select(
+     skipnr, veidarf, lat, lon, yyyy, mm, date, ldate, tegund, afli, togtimi) %>%
+   left_join(lesa_tegundir(con)) %>%
+   select(-c(yfir_flokkur, visindaheiti)) %>%
+   collect(n = Inf) %>%
+   mutate(afli = as.numeric(afli), # otherwise returned as integer
+     mm = month(date),
+     ww = week(date),
+     jul = yday(date)) -> d
Joining, by = "visir"
Joining, by = "visir"
Joining, by = "visir"
Joining, by = "tegund"
Warning messages:
1: `mutate_()` is deprecated as of dplyr 0.7.0.
Please use `mutate()` instead.
See vignette('programming') for more help
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
2: `select_()` is deprecated as of dplyr 0.7.0.
Please use `select()` instead.
```

dplyr::fall__MEÐ_UNDERSKOR_AFTAN_VIÐ eru orðin úrelt

ætli sé óhætt að þurrka út '_' þegar það er notað í mar::föllum og láta annað standa óbreytt?

Siggi

**Comment by sigurdurthorjonsson** [comment]
var að sækja eitthvað nota 'hydro_station' með Sólveigu Magneu, sama á ferðinni:

> hydro_station(con) %>% filter(l_id=="B7-2017") %>% collect(n=Inf) -> tmp1
Warning messages:
1: `mutate_()` is deprecated as of dplyr 0.7.0.
Please use `mutate()` instead.
See vignette('programming') for more help
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
2: `select_()` is deprecated as of dplyr 0.7.0.
Please use `select()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated.

**Comment by bthe** [comment]
Þetta ætti að vera komið núna, þurfti að hnoða `mar:::geo_convert`.
