### ISSUE TITLE
error in mar-view

### ISSUE THREAD

**Issue by sigurdurthorjonsson** [fishvice/mar#15]
getting:

Error in .oci.SendQuery(conn, statement, data = data, prefetch = prefetch,  : 
  ORA-04063: view "FISKAR.STODVAR_MAR_V" has errors

when running:

library(mar)

con <- connect_mar()

# promises
lesa_numer(con) %>%
  filter(tegund %in% c(130,209)) -> n
lesa_lengdir(con) %>%
  filter(tegund %in% c(130,209)) -> l
lesa_kvarnir(con) %>%
  filter(tegund %in% c(130,209)) -> k

# actual data retrieval
n %>%
  left_join(lesa_stodvar(con)) %>%
  collect(n = Inf) -> n

which returned a result last week. I'm guessing that this isn't directly a 'mar' issue, but something is awry in the DB, perhaps?

**Comment by einarhjorleifsson** [comment]
semsagt villa í:
```
tbl_mar(con, "fiskar.stodvar_mar_v")
Error in .oci.SendQuery(conn, statement, data = data, prefetch = prefetch,  : 
  ORA-04063: view "FISKAR.STODVAR_MAR_V" has errors
```

þarf líklega að ræða við rabba

e

**Comment by einarhjorleifsson** [comment]
Villan er vegna ```d2r```, sbr.:
```
> dplyr::tbl(con, dbplyr::in_schema("fiskar", "stodvar")) %>% 
+   dplyr::select_all(tolower) %>% 
+   dplyr::mutate(lon = ifelse(is.na(hift_v_lengd), kastad_v_lengd, (kastad_v_lengd + hift_v_lengd)/2),
+                 lat = ifelse(is.na(hift_n_breidd), kastad_n_breidd, (kastad_n_breidd + hift_n_breidd)/2)) %>% 
+   dplyr::mutate(reitur = nvl(reitur, d2r(lat, lon)), 
+                 smareitur = nvl(smareitur, d2sr(lat, lon) - 10 * d2r(lat, lon)))
Error in .oci.SendQuery(conn, statement, data = data, prefetch = prefetch,  : 
  ORA-00904: "D2R": invalid identifier
```
líklega á það sama við um d2sr.

**Comment by einarhjorleifsson** [comment]
villan liggur oracle megin, beiðni er í vinnslu.
e
