### ISSUE TITLE
Veiðibókarföll lax- og silungsveiði?

### ISSUE THREAD

**Issue by vonStadarhraun** [fishvice/mar#18]
Hvað varð um aðgang að veiðibókinni?
Var þessu bara hent út?

**Comment by vonStadarhraun** [comment]
Sé að föllinn eru þarna og það er hægt að ná í töflur með tbl_mar. Koma ekki inn föll sem á eftir að roxygena?
kv
Jóhannes

**Comment by bthe** [comment]
Já, það vantar 
> #' @export 
í roxygen hausinn. Þessi veiðibókarföll þurfa líka smá ást og umhyggju;)

**Comment by einarhjorleifsson** [comment]
vissi ekki að nokkur væri að nota þessi veidibok_****-föll. tók því (af einhverjum ástæðum) þau út sem "exporteruð" föll. nema hvað, þau eru þarna eins og bjarki bendir á. í bili er hægt að nota:
mar:::veidbok_***
til að nálgast föllin.
einar

**Comment by vonStadarhraun** [comment]
Held að ég sé sá eini. Var samt að reyna að koma fleirum inn í þetta. Ég forkaði og er að setja inn roxygen haus.

**Comment by einarhjorleifsson** [comment]
í fornöld þá voru við bjarki með kúrs upp á veiðó þar sem við sýndum kóða varðandi úrvinnslu á veiðiskýrslum. sjá: https://heima.hafro.is/~einarhj/education/ofcouRse2016/veidiskyrslur.html
(source er á https://github.com/fishvice/ofcouRse2016)
hugmyndafræðin var að sýna að mjög einfalt væri að búa til eitthvurt report template sem emuleraði helstu töflur og myndir sem eru í "standard" veiðóskýrslum. hér eru inntaksgögnin að vísu eitthvert excel skal, sem er jú bara milliliður - nú getur veiðideildin tekið þetta beint úr mar. þarf bara að umskrifa smá kóðann.
ergo: hægt væri auðveldlega að búa til reactive .Rmd template þar sem notandinn þyrfti einungis að tilgreina veiðistað (á??).
e

**Comment by vonStadarhraun** [comment]
Ég hef notað þetta í skýrslum. https://heima.hafro.is/~johannes/hitara2018.html og https://heima.hafro.is/~johannes/mida2019.html.
Það er hægt að spíta ágætis sjálfvirkum skýrslum út úr java-forritinu sem er notað við innslátt. Ég er aðallega að sækja í sveigjanleikan í R-inu.
